export type INodeType = 'fight' | 'fight-boss' | 'shop'
export type INode = {
  type: INodeType
  id: string
  name: string
  cellIndex: number
  cellMapFrame: number
  x: number
  y: number
  enemies?: {
    pool: string[]
    min: number
    max: number
  }
}

const LEVEL_1: INode[] = [
  {
    type: 'fight',
    id: 'desert-1a',
    name: 'Desert 1a',
    cellIndex: 6,
    cellMapFrame: 1,
    x: 0.3,
    y: 0.5,
    enemies: { pool: ['bug'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'desert-1b',
    name: 'Desert 1b',
    cellIndex: 6,
    cellMapFrame: 1,
    x: 0.7,
    y: 0.5,
    enemies: { pool: ['bug'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'desert-2a',
    name: 'Desert 2a',
    cellIndex: 7,
    cellMapFrame: 1,
    x: 0.3,
    y: 0.5,
    enemies: { pool: ['bug'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'desert-2b',
    name: 'Desert 2b',
    cellIndex: 7,
    cellMapFrame: 1,
    x: 0.7,
    y: 0.5,
    enemies: { pool: ['bug'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'desert-3a',
    name: 'Desert 3a',
    cellIndex: 8,
    cellMapFrame: 1,
    x: 0.1,
    y: 0.5,
    enemies: { pool: ['bug', 'snake'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'desert-3b',
    name: 'Desert 3b',
    cellIndex: 8,
    cellMapFrame: 1,
    x: 0.2,
    y: 0.5,
    enemies: { pool: ['bug', 'snake'], min: 1, max: 1 },
  },
  {
    type: 'fight-boss',
    id: 'desert-3c',
    name: 'Desert Boss',
    cellIndex: 8,
    cellMapFrame: 1,
    x: 0.4,
    y: 0.5,
    enemies: { pool: ['anubis'], min: 1, max: 1 },
  },
  {
    type: 'shop',
    id: 'desert-s1',
    name: 'Desert Shop',
    cellIndex: 6,
    cellMapFrame: 1,
    x: 0.4,
    y: 0.8,
  },
  {
    type: 'shop',
    id: 'desert-s2',
    name: 'Desert Shop 2',
    cellIndex: 7,
    cellMapFrame: 1,
    x: 0.4,
    y: 0.8,
  },
  {
    type: 'shop',
    id: 'desert-s3',
    name: 'Desert Shop 3',
    cellIndex: 8,
    cellMapFrame: 1,
    x: 0.4,
    y: 0.8,
  },
]

const LEVEL_2: INode[] = [
  {
    type: 'fight',
    id: 'forest-1a',
    name: 'Forest 1a',
    cellIndex: 5,
    cellMapFrame: 2,
    x: 0.3,
    y: 0.5,
    enemies: { pool: ['spider'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'forest-1b',
    name: 'Forest 1b',
    cellIndex: 5,
    cellMapFrame: 2,
    x: 0.7,
    y: 0.5,
    enemies: { pool: ['spider'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'forest-2a',
    name: 'Forest 2a',
    cellIndex: 4,
    cellMapFrame: 2,
    x: 0.3,
    y: 0.5,
    enemies: { pool: ['spider'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'forest-2b',
    name: 'Forest 2b',
    cellIndex: 4,
    cellMapFrame: 2,
    x: 0.5,
    y: 0.5,
    enemies: { pool: ['spider'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'forest-2c',
    name: 'Forest 2c',
    cellIndex: 4,
    cellMapFrame: 2,
    x: 0.7,
    y: 0.5,
    enemies: { pool: ['spider'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'forest-3a',
    name: 'Forest 3a',
    cellIndex: 3,
    cellMapFrame: 2,
    x: 0.1,
    y: 0.5,
    enemies: { pool: ['spider', 'snail'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'forest-3b',
    name: 'Forest 3b',
    cellIndex: 3,
    cellMapFrame: 2,
    x: 0.2,
    y: 0.5,
    enemies: { pool: ['spider', 'snail'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'forest-3c',
    name: 'Forest 3c',
    cellIndex: 3,
    cellMapFrame: 2,
    x: 0.3,
    y: 0.5,
    enemies: { pool: ['spider', 'snail'], min: 1, max: 1 },
  },
  {
    type: 'fight-boss',
    id: 'forest-3d',
    name: 'Forest Boss',
    cellIndex: 3,
    cellMapFrame: 2,
    x: 0.4,
    y: 0.5,
    enemies: { pool: ['knight'], min: 1, max: 1 },
  },
  {
    type: 'shop',
    id: 'forest-s1',
    name: 'Forest Shop',
    cellIndex: 5,
    cellMapFrame: 2,
    x: 0.4,
    y: 0.8,
  },
  {
    type: 'shop',
    id: 'forest-s2',
    name: 'Forest Shop 2',
    cellIndex: 4,
    cellMapFrame: 2,
    x: 0.4,
    y: 0.8,
  },
  {
    type: 'shop',
    id: 'forest-s3',
    name: 'Forest Shop 3',
    cellIndex: 3,
    cellMapFrame: 2,
    x: 0.4,
    y: 0.8,
  },
]

const LEVEL_3: INode[] = [
  {
    type: 'fight',
    id: 'mountain-1a',
    name: 'Mountain 1a',
    cellIndex: 0,
    cellMapFrame: 3,
    x: 0.3,
    y: 0.5,
    enemies: { pool: ['roller'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'mountain-1b',
    name: 'Mountain 1b',
    cellIndex: 0,
    cellMapFrame: 3,
    x: 0.7,
    y: 0.5,
    enemies: { pool: ['roller'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'mountain-1c',
    name: 'Mountain 1c',
    cellIndex: 0,
    cellMapFrame: 3,
    x: 0.5,
    y: 0.5,
    enemies: { pool: ['roller'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'mountain-2a',
    name: 'Mountain 2a',
    cellIndex: 1,
    cellMapFrame: 3,
    x: 0.1,
    y: 0.5,
    enemies: { pool: ['roller', 'ogre'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'mountain-2b',
    name: 'Mountain 2b',
    cellIndex: 1,
    cellMapFrame: 3,
    x: 0.2,
    y: 0.5,
    enemies: { pool: ['roller', 'ogre'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'mountain-2c',
    name: 'Mountain 2c',
    cellIndex: 1,
    cellMapFrame: 3,
    x: 0.3,
    y: 0.5,
    enemies: { pool: ['roller', 'ogre'], min: 1, max: 1 },
  },
  {
    type: 'fight-boss',
    id: 'mountain-2d',
    name: 'Mountain Boss',
    cellIndex: 1,
    cellMapFrame: 3,
    x: 0.4,
    y: 0.5,
    enemies: { pool: ['golem'], min: 1, max: 1 },
  },
  {
    type: 'shop',
    id: 'mountain-s1',
    name: 'Mountain Shop',
    cellIndex: 0,
    cellMapFrame: 3,
    x: 0.4,
    y: 0.8,
  },
  {
    type: 'shop',
    id: 'mountain-s2',
    name: 'Mountain Shop 2',
    cellIndex: 1,
    cellMapFrame: 3,
    x: 0.4,
    y: 0.8,
  },
]

const LEVEL_4: INode[] = [
  {
    type: 'fight',
    id: 'castle-2a',
    name: 'Castle 2a',
    cellIndex: 2,
    cellMapFrame: 4,
    x: 0.1,
    y: 0.5,
    enemies: { pool: ['zombie', 'skeleton'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'castle-2b',
    name: 'Castle 2b',
    cellIndex: 2,
    cellMapFrame: 4,
    x: 0.2,
    y: 0.5,
    enemies: { pool: ['zombie', 'skeleton'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'castle-2c',
    name: 'Castle 2c',
    cellIndex: 2,
    cellMapFrame: 4,
    x: 0.3,
    y: 0.5,
    enemies: { pool: ['zombie', 'skeleton'], min: 1, max: 1 },
  },
  {
    type: 'fight',
    id: 'castle-2d',
    name: 'Castle 2d',
    cellIndex: 2,
    cellMapFrame: 4,
    x: 0.5,
    y: 0.5,
    enemies: { pool: ['zombie', 'skeleton'], min: 1, max: 1 },
  },
  {
    type: 'fight-boss',
    id: 'castle-2e',
    name: 'Castle Boss',
    cellIndex: 2,
    cellMapFrame: 4,
    x: 0.6,
    y: 0.5,
    enemies: { pool: ['death'], min: 1, max: 1 },
  },
  {
    type: 'shop',
    id: 'castle-s1',
    name: 'Castle Shop',
    cellIndex: 2,
    cellMapFrame: 4,
    x: 0.4,
    y: 0.8,
  },
]

export const MAP_DATA: INode[] = [
  ...LEVEL_1,
  ...LEVEL_2,
  ...LEVEL_3,
  ...LEVEL_4,
]
